# Generated by Django 3.0 on 2019-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_catelogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
