# Generated by Django 2.2.1 on 2019-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_catelogue', '0002_auto_20191215_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(default='test', max_length=256),
        ),
        migrations.AddField(
            model_name='products',
            name='serial_no',
            field=models.CharField(default='test', max_length=256),
        ),
    ]
